# action.yml
name: 'Publish runtime to Aleph'
description: 'Publish runtime to Aleph ecosystem'
inputs:
  private_key:
    description: 'Private key to use in Aleph client'
    required: true
    default: 'XXXXXXX'
  runtime_filename:
    description: 'Runtime filename to publish, pin and use'
    required: true
    default: 'rootfs.squashfs'
  docker_compose_url:
    description: 'Url of the docker-compose.yml file to use for the image'
    required: false
    default: ''
  env_url:
    description: 'Url of the .env file to use for the image'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.runtime_filename }}
    - ${{ inputs.private_key }}
    - ${{ inputs.docker_compose_url }}
    - ${{ inputs.env_url }}
