# action.yml
name: 'Publish runtime to Aleph'
description: 'Publish runtime to Aleph ecosystem'
inputs:
  private_key:
    description: 'Private key to use in Aleph client'
    required: true
    default: 'XXXXXXX'
  runtime_filename:
    description: 'Runtime filename to publish, pin and use'
    required: true
    default: 'rootfs.squashfs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.runtime_filename }}
    - ${{ inputs.private_key }}
