# action.yml
name: 'Create Aleph Docker Runtime'
description: 'Create Aleph Docker Runtime implementing some images'
inputs:
  docker-lib-path:
    description: 'Path to find the /var/lib/docker files to create the root filesystem'
    required: false
    default: '/tmp/'
  file-name:
    description: 'File name of /var/lib/docker tar file'
    required: false
    default: 'aleph-framework-var-lib-docker.tar.gz'
  output-path:
    description: 'Path to save the runtime filesystem'
    required: false
    default: '/tmp/rootfs.squashfs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docker-lib-path }}
    - ${{ inputs.file-name }}
    - ${{ inputs.output-path }}
