name: Test Publish Static

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate random bytes
        run: node publish-static/tests/e2e/generateRandomBytes.js

      - name: Display execution files
        run: ls
